export const carNames: string[] = [
  "Toyota Camry",
  "Honda Civic",
  "Ford Mustang",
  "Chevrolet Corvette",
  "BMW 3 Series",
  "Mercedes-Benz C-Class",
  "Audi A4",
  "Nissan Altima",
  "Volkswagen Golf",
  "Tesla Model S",
  "Jeep Wrangler",
  "Subaru Outback",
  "Mazda MX-5",
  "Hyundai Sonata",
  "Kia Optima",
  "Lexus RX",
  "Volvo XC90",
  "Porsche 911",
  "Ferrari 458",
  "Lamborghini Huracan",
  "Maserati GranTurismo",
  "Cadillac Escalade",
  "Lincoln Navigator",
  "Land Rover Range Rover",
  "Bentley Continental GT",
];

export const carColors: string[] = [
  "black",
  "silver",
  "gray",
  "white",
  "maroon",
  "red",
  "purple",
  "fuchsia",
  "green",
  "lime",
  "olive",
  "yellow",
  "navy",
  "blue",
  "teal",
  "aqua",
];
